"""added activities model

Revision ID: 45896e2af290
Revises: e587cbffbbee
Create Date: 2023-01-13 12:20:07.577611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45896e2af290'
down_revision = 'e587cbffbbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cardId'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('lists', 'card_order',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'card_order',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('activities')
    # ### end Alembic commands ###
