"""add card_order

Revision ID: e587cbffbbee
Revises: 2aaa10ff355c
Create Date: 2023-01-11 09:55:14.248013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e587cbffbbee'
down_revision = '2aaa10ff355c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('card_order', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'card_order')
    # ### end Alembic commands ###
